theme: minima
title: blog
author:
  name: Sparrow0hawk
  email: alexjcoleman@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  A quick, simple blog site

show_excerpts: false # set to true to show excerpts on the homepage
